scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: footprint_filter
      type: laser_filters/LaserScanFootprintFilter
      params:
        inscribed_radius: 0.275

    filter2:
      name: range
      type: laser_filters/LaserScanRangeFilter
      params:
        lower_threshold: 0.01
        upper_threshold: 25.0
        lower_replacement_value: -.inf
        upper_replacement_value: .inf

    # filter3:
    #   name: outlier
    #   type: pal_filters/LaserScanOutlierFilter
    #   params:
    #     distance_threshold: 0.5
    #     resolution: 0.1
    #     min_x: -3.0
    #     max_x:  3.0
    #     min_y: -3.0
    #     max_y:  3.0
    #     max_n:  2
